version: '3.8'

services:
  mongodb:
    image: mongo:5.0.27
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      -  ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example