version: '3.8'

services:
  mongodb:
    image: mongo:5.0.27
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      -  ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mock-server:
    build:
      dockerfile: Dockerfile.mock
    container_name: mock-server
    command: fastapi dev mock_server.py --port 8001
    port:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - db
  lead-server:
    build:
      dockerfile: Dockerfile.main
    container_name: lead-server
    command: fastapi dev server.py --port 8000
    port:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - mongo
      - mock-server